#!/usr/bin/env python3
"""VoxLogicA 1 against VoxLogicA 2 on the BraTS threshold sweep.

VoxLogicA 1 has no loops, no `dir` and no sequences, so it cannot run the
sweep program as written. This script writes the sweep out by hand for it:
one program per case, in which the 21 values of the permissive threshold are
unrolled into 21 printed Dice values. It writes the VoxLogicA 2 program for
the same case from the same template, with the same constants, the same
operators and the same goal names, and one VoxLogicA 2 program that does all
the cases in one process, which is how VoxLogicA 2 is meant to be used.

The two tools are measured by the same code (``suite.py``: wall, CPU and peak
memory from ``os.wait4``, quiet-machine gate, foreign-load sampling), and
their answers are compared value by value: a speed comparison between two
programs that compute different numbers would mean nothing.

WHY NOT THE GALLERY PROGRAM'S OPERATORS. The sweep in the gallery smooths with
VoxLogicA 2's `smoothen`, which VoxLogicA 1 does not have. Both sides here use
VoxLogicA 1's own definition of the same smoothing (`flt`, built from distance
transforms), which the differential kit has shown to agree between the two
tools to ten digits. The comparison is therefore between engines, not between
two smoothings.

USAGE
  python3 tools/perf/vl1_compare.py --vl1 /path/to/VoxLogicA_1.3.3-..._linux-x64 \\
      --dataset /path/to/MICCAI_BraTS2020_TrainingData --cases 20 --reps 3 \\
      --out DIR --work-dir DIR2

OUTPUT (``--out``): as ``suite.py`` (meta.json, runs.jsonl, logs/), plus
``programs/`` and ``agreement.json`` (largest difference between the tools).
Records have experiment ``vl1``; configurations ``vl1-cNNN``, ``vl2-cNNN``
and ``vl2-all``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import socket
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import suite  # noqa: E402

THRESHOLDS = [t / 100 for t in range(72, 93)]   # the sweep's 0.72 ... 0.92


def case_paths(dataset: Path, case: int) -> tuple[str, str]:
    name = f"BraTS20_Training_{case:03d}"
    return (str(dataset / name / f"{name}_flair.nii.gz"),
            str(dataset / name / f"{name}_seg.nii.gz"))


def goal(case: int, t: float) -> str:
    return f"dice_c{case:03d}_t{round(t * 100)}"


def vl1_program(dataset: Path, case: int, hi: float) -> str:
    flair, seg = case_paths(dataset, case)
    lines = [
        "// Generated by tools/perf/vl1_compare.py -- one case of the threshold sweep.",
        'import "stdlib.imgql"',
        "let dice(x,y) = (2 .*. volume(x & y)) ./. (volume(x) .+. volume(y))",
        "let distlt(x,y) = dt(y) <. x",
        "let grow2(a,b) = (a|touch(b,a))",
        "let flt(r,a) = distlt(r,distgeq(r,!a))",
        f'load imgFLAIR = "{flair}"',
        f'load imgSeg = "{seg}"',
        "let flair = intensity(imgFLAIR)",
        "let gt = intensity(imgSeg) >. 0",
        "let pflair = percentiles(flair, !touch(flair <. 0.1, border), 0.5)",
        f"let hyper = flt(5.0, pflair >. {hi})",
    ]
    for t in THRESHOLDS:
        lines.append(f'print "{goal(case, t)}" dice(grow2(hyper, flt(2.0, pflair >. {t})), gt)')
    return "\n".join(lines) + "\n"


VL2_PRELUDE = """\
// Generated by tools/perf/vl1_compare.py -- the threshold sweep in VoxLogicA 1's
// operators, so that both tools compute the same numbers.
import "simpleitk"
import "vox1"
distlt(x, y) = dt(y) <. x
flt(r, a) = distlt(r, distgeq(r, not(a)))
dice(x, y) = (2 * volume(and(x, y))) / (volume(x) + volume(y))
"""


def vl2_case(dataset: Path, case: int, hi: float) -> str:
    flair, seg = case_paths(dataset, case)
    lines = [
        f'flair_{case} = intensity(ReadImage("{flair}"))',
        f'gt_{case} = geq_sv(1, intensity(ReadImage("{seg}")))',
        f"pflair_{case} = percentiles(flair_{case}, "
        f"not(touch(leq_sv(0.1, flair_{case}), border(flair_{case}))), 0.5)",
        f"hyper_{case} = flt(5.0, geq_sv({hi}, pflair_{case}))",
    ]
    for t in THRESHOLDS:
        lines.append(f'print "{goal(case, t)}" '
                     f"dice(grow(hyper_{case}, flt(2.0, geq_sv({t}, pflair_{case}))), gt_{case})")
    return "\n".join(lines) + "\n"


def compare(records: list[dict], logs: Path, tolerance: float) -> dict:
    """Largest difference between any two runs on any goal they share."""
    values: dict[str, dict[str, float]] = {}
    for r in records:
        if r["ended_by"] != "exit" or r["exit_code"] != 0:
            continue
        tool = r["config"].split("-")[0]
        goals = json.loads((logs / f"{r['run_id']}.goals.json").read_text())
        for name, value in goals.items():
            values.setdefault(name, {}).setdefault(tool, float(value))
    worst, worst_goal, missing = 0.0, None, []
    for name, by_tool in values.items():
        if len(by_tool) < 2:
            missing.append(name)
            continue
        spread = max(by_tool.values()) - min(by_tool.values())
        if spread > worst:
            worst, worst_goal = spread, name
    return {"goals_compared": len(values) - len(missing), "goals_missing_a_side": missing,
            "max_abs_difference": worst, "worst_goal": worst_goal, "tolerance": tolerance,
            "agree": worst <= tolerance and not missing}


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--vl1", type=Path, required=True, help="VoxLogicA 1 binary directory")
    p.add_argument("--dataset", type=Path, required=True)
    p.add_argument("--cases", type=int, default=20)
    p.add_argument("--first-case", type=int, default=1)
    p.add_argument("--hi", type=float, default=0.93)
    p.add_argument("--reps", type=int, default=3)
    p.add_argument("--threads", type=int, default=os.cpu_count() or 8,
                   help="VoxLogicA 2 workers (VoxLogicA 1 chooses its own)")
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--work-dir", type=Path, required=True)
    p.add_argument("--engine", type=Path, default=suite.REPO)
    p.add_argument("--engine-python", type=Path, default=None)
    p.add_argument("--quiet-pct", type=float, default=100.0)
    p.add_argument("--hold", type=float, default=60.0)
    p.add_argument("--timeout", type=float, default=4 * 3600)
    p.add_argument("--tolerance", type=float, default=1e-8,
                   help="largest Dice difference accepted (VoxLogicA 1 prints 10 digits)")
    p.add_argument("--no-all", action="store_true",
                   help="skip the single VoxLogicA 2 process over all cases")
    a = p.parse_args(argv[1:])
    a.engine = a.engine.resolve()
    a.engine_python = a.engine_python or a.engine / ".venv" / "bin" / "python"
    if a.out.exists():
        p.error(f"{a.out} exists; results are never overwritten")
    for path in (a.out.parent, a.work_dir.parent if not a.work_dir.exists() else a.work_dir):
        if suite.fs_type(path) in ("tmpfs", "ramfs"):
            p.error(f"{path} is on tmpfs")
    a.out.mkdir(parents=True)

    cases = list(range(a.first_case, a.first_case + a.cases))
    progs = a.out / "programs"
    progs.mkdir()
    for c in cases:
        (progs / f"vl1-c{c:03d}.imgql").write_text(vl1_program(a.dataset, c, a.hi))
        (progs / f"vl2-c{c:03d}.imgql").write_text(VL2_PRELUDE + vl2_case(a.dataset, c, a.hi))
    (progs / "vl2-all.imgql").write_text(
        VL2_PRELUDE + "".join(vl2_case(a.dataset, c, a.hi) for c in cases))

    # The suite's runner, configured for this measurement.
    s_args = argparse.Namespace(
        out=a.out, work_dir=a.work_dir, keep_stores=False, engine=a.engine,
        engine_python=a.engine_python, engine_arg=[], itk_threads=0,
        quiet_pct=a.quiet_pct, hold=a.hold, timeout=a.timeout)
    s = suite.Suite(s_args)
    vl1_bin = a.vl1 / "VoxLogicA"
    meta = {
        "suite": "tools/perf/vl1_compare.py", "argv": sys.argv,
        "started_at": time.strftime("%Y-%m-%d %H:%M:%S %z"), "host": socket.gethostname(),
        "machine": {"cpu_model": suite.cpu_model(), "logical_cpus": os.cpu_count(),
                    "mem_total_gb": suite.mem_total_gb()},
        "work_dir_fs": suite.fs_type(a.work_dir),
        "engine": suite.engine_info(a.engine, a.engine_python),
        "vl1": {"path": str(a.vl1), "sha256": hashlib.sha256(
            (a.vl1 / "VoxLogicA.dll").read_bytes()).hexdigest()
            if (a.vl1 / "VoxLogicA.dll").exists() else None},
        "settings": {"cases": cases, "hi": a.hi, "thresholds": THRESHOLDS, "reps": a.reps,
                     "threads_vl2": a.threads, "hold_s": a.hold, "quiet_pct": a.quiet_pct},
    }
    (a.out / "meta.json").write_text(json.dumps(meta, indent=2))
    s.log(f"VoxLogicA 1 at {a.vl1}; VoxLogicA 2 {meta['engine']['describe']}; "
          f"{len(cases)} cases x {len(THRESHOLDS)} thresholds, {a.reps} reps")

    def vl1(case: int, rep: int) -> dict:
        prog = progs / f"vl1-c{case:03d}.imgql"
        return s.run("vl1", f"vl1-c{case:03d}", rep, 0, a.work_dir / "unused",
                     command=[str(vl1_bin), str(prog.resolve())], cwd=a.vl1)

    def vl2(config: str, rep: int) -> dict:
        s.program = progs / f"{config}.imgql"
        store = s.store(f"{config}-r{rep}")
        record = s.run("vl1", config, rep, a.threads, store)
        s.discard(store)
        return record

    # Untimed warm-up of both tools: page cache, .NET JIT, Numba.
    s.run("warmup", "vl1", 0, 0, a.work_dir / "unused",
          command=[str(vl1_bin), str((progs / f"vl1-c{cases[0]:03d}.imgql").resolve())],
          cwd=a.vl1)
    vl2(f"vl2-c{cases[0]:03d}", 0)

    records = []
    for rep in range(1, a.reps + 1):
        for i, c in enumerate(cases):
            pair = [lambda c=c: vl1(c, rep), lambda c=c: vl2(f"vl2-c{c:03d}", rep)]
            if (rep + i) % 2:
                pair.reverse()   # neither tool always runs first, i.e. on a warmer machine
            records += [f() for f in pair]
        if not a.no_all:
            records.append(vl2("vl2-all", rep))

    agreement = compare(records, s.logs, a.tolerance)
    (a.out / "agreement.json").write_text(json.dumps(agreement, indent=2))
    meta["finished_at"] = time.strftime("%Y-%m-%d %H:%M:%S %z")
    (a.out / "meta.json").write_text(json.dumps(meta, indent=2))
    s.log(f"agreement: {agreement['goals_compared']} goals, max difference "
          f"{agreement['max_abs_difference']:.2e} ({'AGREE' if agreement['agree'] else 'DISAGREE'})")
    return 0 if agreement["agree"] else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
