#!/usr/bin/env python3
"""Build the TACAS artifact directory from this checkout, repeatably.

Run it as often as you like: the engine is still moving, so the artifact is a
BUILD PRODUCT, not a directory anyone edits by hand. Nothing here is copied out
of a previous artifact -- every run starts from the working tree, so what you
ship is what the repository says today.

    python3 tools/make_artifact.py                 # code + programs
    python3 tools/make_artifact.py --with-model    # ... and the trained weights
    python3 tools/make_artifact.py --tar           # ... and a tarball beside it

Stdlib only, and plain `python3`: this must work before `bootstrap.py` has
built anything.

WHAT IT REFUSES TO DO. BraTS may not be redistributed, so the script never
copies image data, and it says so rather than quietly skipping: the five-case
sampler's `data/` directory is symlinks into the dataset, and nnU-Net's
`nnUNet_raw`/`nnUNet_preprocessed` trees are BraTS volumes rewritten. Only the
trained weights leave, and only when asked.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tarfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: Marks a directory as ours to overwrite. Without it the script will not
#: delete anything: pointing --out at a home directory should not be fatal.
MARKER = ".voxlogica-artifact"

# --------------------------------------------------------------- manifest ---
# Edit these four lists as the tree moves. Everything else follows from them.

#: What makes the tool run. Paths are repo-relative and keep their layout in
#: the artifact, so a program's relative imports and paths still resolve.
ENGINE: list[str] = [
    "voxlogica",                              # the launcher
    "bootstrap.py",                           # builds .venv, fetches uv
    ".python-version",                        # 3.14t -- free-threaded, required
    "implementation/python/voxlogica",        # the engine itself
    "implementation/python/requirements.txt",
    # The locks, not just the requirements: requirements.txt says what we depend
    # on, the lock says what THOSE depend on, with hashes. Only the second makes
    # a rebuild months from now resolve the stack these numbers came from.
    "implementation/python/requirements.lock",
    "implementation/python/requirements-test.lock",
]

#: The experiments, in the order the README presents them. `needs_dataset`
#: drives what the README tells the reviewer to obtain.
PROGRAMS: list[dict] = [
    {
        "path": "doc/gallery/programs/nnunet/nnunet-circle-segmentation.imgql",
        "title": "Smoke test",
        "needs_dataset": False,
        "minutes": "15-25",
        "note": "Synthetic circles and squares. No data of any kind: the images are "
                "generated by the program. It trains a small nnU-Net on the CPU and "
                "predicts with it, so a green run proves the whole install -- engine, "
                "SimpleITK, torch, nnU-Net. Run this one first.",
        "outputs": "output/nnunet-circle-segmentation/",
        "expect": [
            "10 files under `training/` -- `case_0..4_image.png` and `case_0..4_label.png`",
            "2 files under `predictions/` -- `test_a_input.png`, `test_b_input.png`",
            "2 more under `predictions/` -- `test_a_segmentation.png`, "
            "`test_b_segmentation.png`, each a white blob where the network found "
            "the circle",
        ],
        "total_files": 14,
    },
    {
        "path": "doc/gallery/programs/brats2020/brats-five-cases.imgql",
        "title": "TACAS recipe, five BraTS2020 cases",
        "needs_dataset": True,
        "minutes": "2-5",
        "note": "The published whole-tumour recipe on FLAIR alone, scored per case "
                "against the ground truth. Five cases, so it answers 'is the method "
                "reproducing' in minutes rather than in an hour.",
        "outputs": "case_230_segmentation.nii.gz (beside the program)",
        "expect": [
            "one `case_*_best` goal per case, each a Dice score",
            "`average_best`, the mean of those five",
            "`case_230_sweep`, one Dice per candidate threshold",
        ],
        "total_files": 1,
    },
    {
        "path": "doc/gallery/programs/simpleitk/brats-threshold-sweep-aiim.imgql",
        "title": "AIIM threshold sweep",
        "needs_dataset": True,
        "minutes": "60-170",
        "note": "The AIIM study as one declarative program: sweep the permissive "
                "threshold over 0.72-0.92, keep the best per case, and report the "
                "spread of the winning thresholds. This is the paper's experiment.",
        "outputs": "output/aiim-sweep/",
        "expect": [
            "`dice_fixed_mean` -- the single published threshold, scored",
            "`dice_best_mean`, `dice_best_median`, `dice_best_stdev` -- the per-case best",
            "`vi_thr_distribution` -- which thresholds won, and how often. A SPREAD "
            "here rather than one winner is the study's result",
            "36 PNGs under `output/aiim-sweep/`, three planes for each of the ten "
            "worst cases",
        ],
        "total_files": 36,
    },
]

#: Trained weights, so a reviewer without the dataset can still predict.
#: `keep` is an allowlist BY FILENAME: everything else under the source tree is
#: left behind, which is what keeps BraTS-derived volumes out.
MODEL = {
    "source": Path.home() / "nnunet-brats-smoke" / "nnUNet_results",
    "dest": "model/nnUNet_results",
    "keep": {"checkpoint_final.pth", "dataset.json", "dataset_fingerprint.json",
             "plans.json"},
    #: Named so the refusal can be explained, not just performed.
    "refused": ["nnUNet_raw", "nnUNet_preprocessed"],
}

#: Never copied, wherever they appear.
EXCLUDE_NAMES = {"__pycache__", ".pytest_cache", ".mypy_cache", ".DS_Store"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo"}

#: A program with no `print`/`save` computes nothing and exits 0 (the engine now
#: refuses it). Catching that here keeps a dud out of the artifact.
GOAL_RE = re.compile(r"^[ \t]*(print|save)[ \t]", re.MULTILINE)
#: Absolute dataset paths are machine-specific; the README must list them.
DATASET_RE = re.compile(r"^\s*(\w*dataset_root|work_root)\s*=\s*\"([^\"]+)\"", re.MULTILINE)


# ------------------------------------------------------------------ steps ---
def step(n: int, text: str) -> None:
    print(f"\n[{n}] {text}", flush=True)


def _skip(path: Path) -> bool:
    return path.name in EXCLUDE_NAMES or path.suffix in EXCLUDE_SUFFIXES


def copy_tree(src: Path, dst: Path) -> tuple[int, int]:
    """Copy a file or directory, dropping caches. Returns (files, bytes)."""
    if src.is_file():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst, follow_symlinks=True)
        return 1, dst.stat().st_size
    files = total = 0
    for item in sorted(src.rglob("*")):
        if any(_skip(p) for p in (item, *item.parents)):
            continue
        target = dst / item.relative_to(src)
        if item.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif item.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, target, follow_symlinks=True)
            files += 1
            total += target.stat().st_size
    return files, total


def git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=REPO, capture_output=True,
                              text=True, check=True).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def human(n: float) -> str:
    for unit in ("B", "KB", "MB"):
        if n < 1024:
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024.0
    return f"{n:.1f} GB"


def prepare_out(out: Path, force: bool) -> None:
    """Make an empty output directory, refusing to delete what we did not make."""
    if out.exists():
        if not (out / MARKER).exists() and not force:
            sys.exit(f"refusing to overwrite {out}: not a previous artifact build "
                     f"(no {MARKER}). Use --force, or pick another --out.")
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text("built by tools/make_artifact.py\n", encoding="utf-8")


def check_programs(out: Path):
    """Report programs that compute nothing, their goal counts, and the paths a
    reviewer must set. Counted from the COPIED files, so the README describes
    the artifact rather than the checkout."""
    dud, paths, goals = [], [], {}
    for spec in PROGRAMS:
        text = (out / spec["path"]).read_text(encoding="utf-8")
        goals[spec["path"]] = len(GOAL_RE.findall(text))
        if not goals[spec["path"]]:
            dud.append(spec["path"])
        for name, value in DATASET_RE.findall(text):
            paths.append((spec["path"], name, value))
    return dud, paths, goals


def write_checksums(out: Path) -> int:
    lines, count = [], 0
    for item in sorted(out.rglob("*")):
        if item.is_file() and item.name not in {"SHA256SUMS", MARKER}:
            digest = hashlib.sha256(item.read_bytes()).hexdigest()
            lines.append(f"{digest}  {item.relative_to(out).as_posix()}")
            count += 1
    (out / "SHA256SUMS").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count


def write_readme(out: Path, paths: list[tuple[str, str, str]],
                 goals: dict[str, int], with_model: bool) -> None:
    lock = out / "implementation/python/requirements.lock"
    n_locked = (len(re.findall(r"^[a-zA-Z].*==", lock.read_text(encoding="utf-8"),
                               re.MULTILINE)) if lock.exists() else 0)
    """Write the reviewer's instructions: one numbered section per experiment.

    Generated rather than kept by hand, so it cannot drift from the manifest:
    the table, the commands and the goal counts all come from PROGRAMS and from
    the copied files themselves.
    """
    index_rows = "\n".join(
        f"| {i} | {s['title']} | {'BraTS2020' if s['needs_dataset'] else '**none**'} "
        f"| {s['minutes']} min | {goals[s['path']]} |"
        for i, s in enumerate(PROGRAMS, 1))

    sections = []
    for i, spec in enumerate(PROGRAMS, 1):
        expect = "\n".join(f"- {e}" for e in spec["expect"])
        data_line = ("This program needs **no data**. If it fails, the problem is the\n"
                     "install, not the dataset.\n"
                     if not spec["needs_dataset"] else
                     "This program needs BraTS 2020. Set its path first -- see section B.\n")
        sections.append(f"""### {i}. {spec['title']}

{spec['note']}

{data_line}
```bash
./voxlogica run {spec['path']}
```

Expected: **exit status 0**, {goals[spec['path']]} named goal{'' if goals[spec['path']] == 1 else 's'} printed as JSON,
and {spec['total_files']} file{'' if spec['total_files'] == 1 else 's'} under
`{spec['outputs']}`. Roughly {spec['minutes']} minutes.

What a good run shows:

{expect}

Check the files:

```bash
find {spec['outputs'].split()[0]} -type f | wc -l     # {spec['total_files']}
```

A count lower than that means some writes were never demanded, not that they
failed -- see section D.

""")

    to_edit = "\n".join(f"| `{p}` | `{n}` | `{v}` |" for p, n, v in paths) or \
              "| — | — | none found |"

    model_section = (
        "`model/nnUNet_results` holds trained weights, so the nnU-Net programs can\n"
        "predict without you retraining. Point nnU-Net at it before running:\n\n"
        "```bash\nexport nnUNet_results=\"$PWD/model/nnUNet_results\"\n```\n\n"
        "The data it was trained on is NOT here and cannot be: it is BraTS, rewritten.\n"
        if with_model else
        "Not included in this build. Rebuild with `--with-model` to add it.\n")

    (out / "README.md").write_text(f"""# VoxLogicA-2 — TACAS artifact

Built from the repository by `tools/make_artifact.py`; `PROVENANCE.json` records
the exact commit.

| # | experiment | data needed | time | goals |
|---|---|---|---|---|
{index_rows}

Read sections A and B once, then run the experiments in order. **Experiment 1
needs nothing but this directory** -- start there.

---

## A. Build the tool

```bash
./voxlogica --help
```

The first call runs `bootstrap.py`, which downloads a pinned `uv`, reads
`.python-version` and creates `.venv` here. Expect a few minutes and a few GB.
It is idempotent: re-run it freely.

Every version is pinned. `implementation/python/requirements.lock` resolves the
whole transitive graph -- {n_locked} packages, each with its sha256 -- and that
is what gets installed. A package re-uploaded under the same version fails the
install rather than substituting itself. The last line of the bootstrap output
says which path was taken; it must read

```
Environment synchronized with the hashed lock files.
```

If it instead mentions `requirements.txt (NO LOCK FILE ...)`, the lock did not
travel with this artifact and versions can drift. Say so in your review.

Two things that are not negotiable:

1. **Free-threaded CPython.** `.python-version` asks for `3.14t`. The engine
   refuses a stock build rather than running serialized, and says so.
2. **Always launch through `./voxlogica`.** It exports `PYTHON_GIL=0` before
   the interpreter starts (too late to set from Python) and puts `.venv/bin` on
   `PATH`, which is where nnU-Net's own executables live. Calling
   `python -m voxlogica.main` directly appears to work and then fails inside
   nnU-Net with `No such file or directory: nnUNetv2_plan_and_preprocess`.

## B. Point the programs at your copy of BraTS

The datasets are not here: the BraTS data-use agreement does not let us
redistribute them, so you have to obtain them from the challenge organisers.
Experiment 1 needs none of this.

Each program names its dataset root as a literal near the top. These are the
lines to edit:

| program | variable | value as shipped |
|---|---|---|
{to_edit}

The five-case sampler additionally wants five specific cases in
`doc/gallery/programs/brats2020/data/`, one directory each, exactly as BraTS
ships them; `doc/gallery/programs/brats2020/data/README.md` names the five.

**A wrong path does not pass silently.** `dir` fails when its root does not
exist, and the engine refuses a program whose goals would compute nothing.

## C. Run the experiments

{"".join(sections)}
---

## D. Two things that will confuse you otherwise

**A second run finishes instantly and writes no files.** Results are cached in
`~/.voxlogica`, keyed by content, so re-running an unchanged program returns the
stored values without recomputing -- and therefore without re-writing the
images. That is correct behaviour, not a broken run. To force real computation:

```bash
./voxlogica run --no-cache <program>       # no disk tier at all
```

**Do not run two experiments at the same time.** The nnU-Net programs put their
training tree in a fixed directory under `/tmp`, so two concurrent runs of the
same program share it and corrupt each other's preprocessing. Run them one after
another.

## E. Reproducibility

`--threads N` fixes the degree of parallelism. Results are **bit-identical**
across thread counts -- verified at 1, 4 and 16 threads on experiment 3, and
identical again to a warm-cache run. Only the wall time changes. So a number
that differs on your machine is not the scheduler.

The nnU-Net programs are the exception: GPU non-determinism and training seeds
mean their predictions are not reproducible bit-for-bit unless you use the
shipped weights rather than retraining.

## F. The trained model

{model_section}
## G. Check the shipped files

```bash
sha256sum -c SHA256SUMS
```
""", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the TACAS artifact directory.")
    ap.add_argument("--out", default=str(REPO.parent / "voxlogica-tacas-artifact"),
                    help="output directory (default: beside the repository)")
    ap.add_argument("--with-model", action="store_true",
                    help="include the trained nnU-Net weights (~240 MB)")
    ap.add_argument("--tar", action="store_true", help="also write a .tar.gz beside it")
    ap.add_argument("--force", action="store_true",
                    help="overwrite --out even if this script did not build it")
    args = ap.parse_args()

    out = Path(args.out).expanduser().resolve()
    started = time.time()
    print(f"repository : {REPO}\nartifact   : {out}")

    step(1, f"Preparing {out}")
    prepare_out(out, args.force)

    step(2, f"Copying the engine ({len(ENGINE)} entries)")
    files = size = 0
    for rel in ENGINE:
        src = REPO / rel
        if not src.exists():
            sys.exit(f"missing from the checkout: {rel}")
        f, s = copy_tree(src, out / rel)
        files += f
        size += s
        print(f"    {rel}  ({f} files, {human(s)})")

    step(3, f"Copying {len(PROGRAMS)} programs")
    for spec in PROGRAMS:
        src = REPO / spec["path"]
        if not src.exists():
            sys.exit(f"missing from the checkout: {spec['path']}")
        f, s = copy_tree(src, out / spec["path"])
        files += f
        size += s
        print(f"    {spec['title']}: {spec['path']}")

    step(4, "Placeholder for the five-case sample (no image data is copied)")
    data_dir = out / "doc/gallery/programs/brats2020/data"
    data_dir.mkdir(parents=True, exist_ok=True)
    cases = sorted(p.name for p in (REPO / "doc/gallery/programs/brats2020/data").iterdir()
                   if p.is_dir()) if (REPO / "doc/gallery/programs/brats2020/data").exists() else []
    (data_dir / "README.md").write_text(
        "# The five-case sample\n\n"
        "Empty on purpose. BraTS may not be redistributed, so these five cases have\n"
        "to come from your own copy of MICCAI_BraTS2020_TrainingData. Copy or symlink\n"
        "one directory per case, exactly as BraTS ships them (five files inside:\n"
        "`_flair`, `_t1`, `_t1ce`, `_t2`, `_seg`):\n\n"
        + "".join(f"- `{c}`\n" for c in cases)
        + "\nThe program reads them with `dir(..., recursive)`, so the directory names\n"
          "matter only for your own bookkeeping; the file suffixes matter.\n",
        encoding="utf-8")
    print(f"    named {len(cases)} cases, copied 0 images (BraTS policy)")

    step(5, "Trained model")
    if args.with_model:
        src = MODEL["source"]
        if not src.exists():
            sys.exit(f"--with-model asked for, but {src} does not exist")
        kept = 0
        for item in sorted(src.rglob("*")):
            if item.is_file() and item.name in MODEL["keep"]:
                target = out / MODEL["dest"] / item.relative_to(src)
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, target)
                kept += 1
                files += 1
                size += target.stat().st_size
                print(f"    {item.relative_to(src)}  ({human(target.stat().st_size)})")
        print(f"    kept {kept} files; refused {', '.join(MODEL['refused'])} "
              f"(BraTS-derived volumes)")
    else:
        print("    skipped (pass --with-model to include ~240 MB of weights)")

    step(6, "Checking the programs")
    dud, paths, goals = check_programs(out)
    for program, name, value in paths:
        print(f"    {Path(program).name}: {name} = {value}")
    if dud:
        sys.exit("these programs have no print/save goal and would compute "
                 "nothing:\n  " + "\n  ".join(dud))
    print("    " + ", ".join(f"{Path(s['path']).name}: {goals[s['path']]} goals"
                             for s in PROGRAMS))
    print(f"    {len(paths)} paths for the reviewer to set")

    step(7, "Writing README.md and PROVENANCE.json")
    write_readme(out, paths, goals, args.with_model)
    dirty = bool(git("status", "--porcelain", "--untracked-files=no"))
    (out / "PROVENANCE.json").write_text(json.dumps({
        "built_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "built_by": "tools/make_artifact.py",
        "git_commit": git("rev-parse", "HEAD"),
        "git_branch": git("rev-parse", "--abbrev-ref", "HEAD"),
        "git_describe": git("describe", "--always", "--dirty"),
        "working_tree_dirty": dirty,
        "python_version_file": (REPO / ".python-version").read_text(encoding="utf-8").strip(),
        "builder_python": sys.version.split()[0],
        "programs": [s["path"] for s in PROGRAMS],
        "includes_model": args.with_model,
        "includes_dataset": False,
    }, indent=2) + "\n", encoding="utf-8")
    if dirty:
        print("    WARNING: working tree has uncommitted tracked changes; "
              "the commit in PROVENANCE.json does not describe what was copied")

    step(8, "Writing SHA256SUMS")
    print(f"    {write_checksums(out)} files hashed")

    tarball = None
    if args.tar:
        step(9, "Writing the tarball")
        tarball = out.with_suffix(".tar.gz")
        with tarfile.open(tarball, "w:gz") as tf:
            tf.add(out, arcname=out.name)
        print(f"    {tarball}  ({human(tarball.stat().st_size)})")

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    count = sum(1 for f in out.rglob("*") if f.is_file())
    print(f"\n{'=' * 62}\n"
          f"  artifact   {out}\n"
          f"  files      {count}\n"
          f"  size       {human(total)}\n"
          f"  model      {'included' if args.with_model else 'not included'}\n"
          f"  dataset    never included (BraTS policy)\n"
          + (f"  tarball    {tarball}\n" if tarball else "")
          + f"  built in   {time.time() - started:.1f} s\n"
          f"{'=' * 62}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
