#!/usr/bin/env python3
"""Build the TACAS artifact directory from this checkout, repeatably.

Run it as often as you like: the engine is still moving, so the artifact is a
BUILD PRODUCT, not a directory anyone edits by hand. Nothing here is copied out
of a previous artifact -- every run starts from the working tree, so what you
ship is what the repository says today.

    python3 tools/make_artifact.py                 # code + programs
    python3 tools/make_artifact.py --with-model    # ... and the trained weights
    python3 tools/make_artifact.py --tar           # ... and a tarball beside it

Stdlib only, and plain `python3`: this must work before `bootstrap.py` has
built anything.

WHAT IT REFUSES TO DO. BraTS may not be redistributed, so the script never
copies image data, and it says so rather than quietly skipping: the five-case
sampler's `data/` directory is symlinks into the dataset, and nnU-Net's
`nnUNet_raw`/`nnUNet_preprocessed` trees are BraTS volumes rewritten. Only the
trained weights leave, and only when asked.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tarfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: Marks a directory as ours to overwrite. Without it the script will not
#: delete anything: pointing --out at a home directory should not be fatal.
MARKER = ".voxlogica-artifact"

# --------------------------------------------------------------- manifest ---
# Edit these four lists as the tree moves. Everything else follows from them.

#: What makes the tool run. Paths are repo-relative and keep their layout in
#: the artifact, so a program's relative imports and paths still resolve.
ENGINE: list[str] = [
    "LICENSE",                                # GPL-3.0; the AEC needs one to evaluate at all
    "voxlogica",                              # the launcher
    "bootstrap.py",                           # builds .venv, fetches uv
    ".python-version",                        # 3.14t -- free-threaded, required
    "implementation/python/voxlogica",        # the engine itself
    "implementation/python/requirements.txt",
    # The locks, not just the requirements: requirements.txt says what we depend
    # on, the lock says what THOSE depend on, with hashes. Only the second makes
    # a rebuild months from now resolve the stack these numbers came from.
    "implementation/python/requirements.lock",
    # No requirements-test.lock: tests/ does not ship, so the reviewer's venv
    # is the runtime only. bootstrap.py installs from whichever locks exist.
    # The dataset contract. The programs index cases by POSITION, so which copy
    # of BraTS a reviewer has is part of what the numbers mean.
    "tools/dataset_manifest.py",
    "tools/brats2020-manifest.json",
    # Not an experiment: the one-second program the kick-the-tires phase runs to
    # see the engine COMPUTE something, rather than only parse and typecheck.
    "doc/gallery/programs/default/default-range-map.imgql",
]

#: The experiments, in the order the README presents them. `needs_dataset`
#: drives what the README tells the reviewer to obtain.
PROGRAMS: list[dict] = [
    {
        "path": "doc/gallery/programs/nnunet/nnunet-circle-segmentation.imgql",
        "title": "Installation check, synthetic data",
        "needs_dataset": False,
        "needs_gpu": False,
        # It trains too, so its numbers are no more reproducible than the sweep's.
        # But it has no numbers: it is a pass/fail check that the install works.
        "reproducibility": "pass/fail only",
        "minutes": "51 min on 24 CPU cores, 77 min on 4 (both measured)",
        "note": "Synthetic circles and squares. No data of any kind: the images are "
                "generated by the program. It trains a small nnU-Net on the CPU and "
                "predicts with it, so a green run proves the whole install -- engine, "
                "SimpleITK, torch, nnU-Net. This belongs to the full evaluation, not to "
                "kick-the-tires: it takes about an hour. Start it in the background and "
                "read on.",
        "outputs": "output/nnunet-circle-segmentation/",
        "expect": [
            "10 files under `training/` -- `case_0..4_image.png` and `case_0..4_label.png`",
            "2 files under `predictions/` -- `test_a_input.png`, `test_b_input.png`",
            "2 more under `predictions/` -- `test_a_segmentation.png`, "
            "`test_b_segmentation.png`, each a white blob where the network found "
            "the circle",
        ],
        "total_files": 14,
    },
    {
        "path": "doc/gallery/programs/brats2020/brats-five-cases.imgql",
        "title": "TACAS recipe, five BraTS2020 cases",
        "reproducibility": "bit-identical",
        "needs_dataset": True,
        "minutes": "under a minute (6 s on 24 cores, 31 s on 4)",
        "note": "The published whole-tumour recipe on FLAIR alone, scored per case "
                "against the ground truth. Five cases, so it answers 'is the method "
                "reproducing' in minutes rather than in an hour.",
        "outputs": "case_230_segmentation.nii.gz (beside the program)",
        "expect": [
            "one `case_*_best` goal per case, each a Dice score",
            "`average_best`, the mean of those five",
            "`case_230_sweep`, one Dice per candidate threshold",
        ],
        "total_files": 1,
    },
    {
        "path": "doc/gallery/programs/simpleitk/brats-threshold-sweep-aiim.imgql",
        "title": "AIIM threshold sweep",
        "reproducibility": "bit-identical",
        "needs_dataset": True,
        "minutes": "1-3 min (32 s on 24 cores, 3 min on 4)",
        "note": "The AIIM study as one declarative program: sweep the permissive "
                "threshold over 0.72-0.92, keep the best per case, and report the "
                "spread of the winning thresholds. This is the paper's experiment.",
        "outputs": "output/aiim-sweep/",
        "expect": [
            "`dice_fixed_mean` -- the single published threshold, scored",
            "`dice_best_mean`, `dice_best_median`, `dice_best_stdev` -- the per-case best",
            "`vi_thr_distribution` -- which thresholds won, and how often. A SPREAD "
            "here rather than one winner is the study's result",
            "36 PNGs under `output/aiim-sweep/`, three planes for each of the ten "
            "worst cases",
        ],
        "total_files": 36,
    },
    {
        "path": "doc/gallery/programs/nnunet/brats-threshold-sweep-nnunet.imgql",
        "title": "AIIM sweep against a learned reference",
        "needs_dataset": True,
        "needs_gpu": True,
        "reproducibility": "no -- trains a network",
        "minutes": "~3 min with the shipped weights; hours if retraining",
        "note": "The same sweep as experiment 3, scored against nnU-Net's prediction "
                "instead of the radiologist's annotation. It asks whether the "
                "case-dependence of the permissive threshold survives when the "
                "reference stops being a human annotation. Trains the network first, "
                "unless matching weights are already present.",
        "outputs": "output/aiim-sweep-nnunet/",
        "expect": [
            "`model_dice_mean` -- how close the learned reference is to the "
            "annotation it replaced. Read this FIRST: it bounds everything below, "
            "because a threshold agreeing with a bad model means nothing",
            "`vi_thr_distribution` -- the same question as experiment 3, asked of "
            "the learned reference",
            "`best_dice`, `best_vi_thr` -- per case",
        ],
        "total_files": 40,
    },
]

#: Trained weights, so a reviewer need not repeat the training. `keep` is an
#: allowlist BY FILENAME: everything else under the source tree stays behind,
#: which is what keeps BraTS-derived volumes out.
#:
#: WHAT THESE DO AND DO NOT SAVE. `nnUNetv2_plan_and_preprocess` runs
#: unconditionally in runtime.train_model, BEFORE the per-fold "checkpoint
#: already exists" check, so shipped weights save the TRAINING (the GPU hours),
#: not the dataset: the raw cases are still materialized and preprocessed. A
#: reviewer without BraTS cannot run the nnU-Net program at all.
MODEL = {
    # The work_root the shipped nnU-Net program names, so the weights that get
    # picked up are the ones that program produced. Pointing this elsewhere is
    # how you ship someone else's model by accident; the check below is what
    # catches it when you do.
    "source": Path("/home/laura/nnunet-brats-work") / "nnUNet_results",
    "manifest": Path("/home/laura/nnunet-brats-work") / "voxlogica_manifest.json",
    "dest": "model/nnUNet_results",
    # postprocessing.pkl is THE DECISION, not data: two operation names and the
    # label they apply to, 260 bytes, sitting under fold_0/validation/ beside
    # the validation predictions that are not shipped. Without it the reviewer's
    # run finds nothing to determine postprocessing from and predicts RAW --
    # measured: every aggregate off by 1e-2 against the oracle, the threshold
    # distribution different.
    "keep": {"checkpoint_final.pth", "dataset.json", "dataset_fingerprint.json",
             "plans.json", "postprocessing.pkl"},
    #: Named so the refusal can be explained, not just performed.
    "refused": ["nnUNet_raw", "nnUNet_preprocessed"],
}

#: Weights are reused only when the dataset folder, trainer and configuration
#: all match what the program asks for -- nnU-Net looks them up by that path,
#: and runtime.train_model deliberately refuses another trainer's fold_0
#: ("reusing it would answer the program's question with someone else's
#: answer"). So shipping weights no program can name is shipping 236 MB of
#: nothing, and this is checked rather than hoped for.
MODEL_SETTINGS_RE = {
    "dataset_name": re.compile(r'^\s*dataset_name\s*=\s*"([^"]+)"', re.MULTILINE),
    "trainer": re.compile(r'^\s*nnunet_trainer\s*=\s*"([^"]+)"', re.MULTILINE),
    "configuration": re.compile(r'^\s*nnunet_config\s*=\s*"([^"]+)"', re.MULTILINE),
}

#: What each experiment printed here, so a reviewer can tell "it ran" from
#: "it ran and was right". Kept as data rather than prose so it can be replaced
#: wholesale when we have more runs -- and so the README cannot describe an
#: oracle the manifest does not have.
#:
#: `tolerance` is 0 where repetition has shown the values do not move, and
#: non-zero only where it has shown they do. Do not soften a 0 to make a
#: comparison pass: the whole value of the number is that it is exact.
ORACLE: dict[str, dict] = {
    "doc/gallery/programs/brats2020/brats-five-cases.imgql": {
        "provenance": "Repeated runs, identical. These same values are in "
                      "doc/gallery/programs/brats2020/README.md, measured "
                      "independently and earlier.",
        "tolerance": 0.0,
        "values": [
            ("case_002_best", "0.8959418354477335", "compact, near-median tumour"),
            ("case_079_best", "0.0", "**expected**: smallest tumour in BraTS "
                                     "(7,285 voxels), raises no seed. See below."),
            ("case_089_best", "0.6518925047022751", "most multifocal case"),
            ("case_230_best", "0.9584736373313636", "the median case"),
            ("case_328_best", "0.9131447438872032", "largest tumour"),
            ("average_best", "0.6838905442737151", "mean of the five"),
        ],
        "note": "**A Dice of exactly 0.000 on case 079 is the expected result.** "
                "The method seeds on the top 5% of FLAIR intensity within "
                "the brain and grows from there; a tumour that small raises no seed, "
                "so there is nothing to grow. The case is in the sample to show where "
                "the method does not apply, which a sample of five favourable cases "
                "would hide. If you get 0.000 here, you "
                "have reproduced our result.",
    },
    "doc/gallery/programs/simpleitk/brats-threshold-sweep-aiim.imgql": {
        "provenance": "Six runs across two days: warm cache, empty store, and "
                      "--no-cache at 1, 4 and 16 threads. Bit-identical every time.",
        "tolerance": 0.0,
        "values": [
            ("dice_fixed_mean", "0.8069413698956456", "the single published threshold"),
            ("dice_best_mean", "0.8513501430954795", "per-case best"),
            ("dice_best_median", "0.8904556073150862", ""),
            ("dice_best_stdev", "0.10944800755354497", ""),
            ("vi_thr_mean", "0.89", ""),
            ("vi_thr_median", "0.91", ""),
            ("vi_thr_stdev", "0.03879772103996235", ""),
            ("vi_thr_distribution",
             "[[0.81,2],[0.83,1],[0.85,1],[0.86,1],[0.87,1],[0.88,1],[0.89,1],[0.9,2],[0.92,10]]",
             "**the study's result**: nine thresholds win across twenty cases"),
        ],
        "note": "These are exact. The engine is deterministic in its values: the same "
                "digits came back at every thread count and with the disk cache both "
                "present and absent. A difference here is a real difference, not "
                "scheduling noise -- start with your SimpleITK version.",
    },
    "doc/gallery/programs/nnunet/brats-threshold-sweep-nnunet.imgql": {
        "provenance": "Four independent cold-store runs (2026-09-08 x2, 2026-09-11, "
                      "2026-09-15) on the same trained weights and the same 20 cases; "
                      "the last one on this artifact as a reviewer would run it -- fresh "
                      "checkout, shipped weights, empty store. The values are the "
                      "2026-09-11 run; the others sit within 3.8e-06 of them, the winning "
                      "thresholds identical every time.",
        "tolerance": 1e-4,
        "values": [
            ("model_dice_mean", "0.8587654381227321",
             "how close the learned reference is to the annotation. Read first"),
            ("model_dice_median", "0.9152127540638253", ""),
            ("model_dice_stdev", "0.1101112733588743",
             "large: on some cases the network is weak"),
            ("model_sensitivity_mean", "0.8213030657937151",
             "per case 0.38-0.98: where this is low, the reference is weak"),
            ("model_specificity_mean", "0.9994939855877394", "whole-volume; read differences"),
            ("dice_fixed_mean", "0.8069295235180464", ""),
            ("sensitivity_fixed_mean", "0.9164724040507275", ""),
            ("specificity_fixed_mean", "0.9979484261834999", ""),
            ("dice_best_mean", "0.8501655344839311", ""),
            ("dice_best_median", "0.9258472009239862", ""),
            ("dice_best_stdev", "0.18727288008444662", ""),
            ("sensitivity_best_mean", "0.9431578561623185",
             "the sweep's gain over fixed is almost all recall"),
            ("specificity_best_mean", "0.9973265002479786", "and costs almost nothing here"),
            ("vi_thr_mean", "0.8945000000000001", "**exact**, no tolerance"),
            ("vi_thr_median", "0.9", "**exact**"),
            ("vi_thr_stdev", "0.041986840043543486", "**exact**"),
            ("vi_thr_distribution", "[[0.73,1],[0.87,2],[0.89,4],[0.9,4],[0.91,2],[0.92,7]]",
             "**exact**, and the point of the experiment"),
        ],
        "note": "**What varies between runs, and what does not.** Across three runs the per-case "
                "Dice values differed by at most 2.7e-05 and every aggregate moved in the "
                "sixth decimal or beyond -- while `best_vi_thr` and `vi_thr_distribution` "
                "came back IDENTICAL every time. That is the claim this experiment makes: "
                "the case-dependence of the permissive threshold survives replacing a human "
                "annotation with a learned one, and survives the network being retrained. "
                "Compare the distribution exactly; compare Dice, sensitivity and "
                "specificity to 1e-4 -- and report them to 3-4 decimals, because the "
                "digits past that are noise.\n\n"
                "**Specificity is over the whole volume**, as BraTS scores it, so it is "
                "dominated by the air around the head and sits near 1 for any plausible "
                "segmentation. The differences between rows carry the information; the "
                "absolute level does not.\n\n"
                "**The population is the 293 HGG cases**, selected by the grade in the "
                "dataset's own `name_mapping.csv`, not by directory order. The 20 evaluated "
                "are positions 50-69 of that list, which are BraTS20_Training_051 to _070.",
    },
}

#: Never copied, wherever they appear.
EXCLUDE_NAMES = {"__pycache__", ".pytest_cache", ".mypy_cache", ".DS_Store"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo"}

#: A program with no `print`/`save` computes nothing and exits 0 (the engine now
#: refuses it). Catching that here keeps a dud out of the artifact.
GOAL_RE = re.compile(r"^[ \t]*(print|save)[ \t]", re.MULTILINE)
#: Absolute dataset paths are machine-specific; the README must list them.
DATASET_RE = re.compile(r"^\s*(\w*dataset_root|work_root)\s*=\s*\"([^\"]+)\"", re.MULTILINE)


# ------------------------------------------------------------------ steps ---
def step(n: int, text: str) -> None:
    print(f"\n[{n}] {text}", flush=True)


def _skip(path: Path) -> bool:
    return path.name in EXCLUDE_NAMES or path.suffix in EXCLUDE_SUFFIXES


def copy_tree(src: Path, dst: Path) -> tuple[int, int]:
    """Copy a file or directory, dropping caches. Returns (files, bytes)."""
    if src.is_file():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst, follow_symlinks=True)
        return 1, dst.stat().st_size
    files = total = 0
    for item in sorted(src.rglob("*")):
        if any(_skip(p) for p in (item, *item.parents)):
            continue
        target = dst / item.relative_to(src)
        if item.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif item.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, target, follow_symlinks=True)
            files += 1
            total += target.stat().st_size
    return files, total


def git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=REPO, capture_output=True,
                              text=True, check=True).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def human(n: float) -> str:
    for unit in ("B", "KB", "MB"):
        if n < 1024:
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024.0
    return f"{n:.1f} GB"


def prepare_out(out: Path, force: bool) -> None:
    """Make an empty output directory, refusing to delete what we did not make."""
    if out.exists():
        if not (out / MARKER).exists() and not force:
            sys.exit(f"refusing to overwrite {out}: not a previous artifact build "
                     f"(no {MARKER}). Use --force, or pick another --out.")
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text("built by tools/make_artifact.py\n", encoding="utf-8")


def check_programs(out: Path):
    """Report programs that compute nothing, their goal counts, and the paths a
    reviewer must set. Counted from the COPIED files, so the README describes
    the artifact rather than the checkout."""
    dud, paths, goals = [], [], {}
    for spec in PROGRAMS:
        text = (out / spec["path"]).read_text(encoding="utf-8")
        goals[spec["path"]] = len(GOAL_RE.findall(text))
        if not goals[spec["path"]]:
            dud.append(spec["path"])
        for name, value in DATASET_RE.findall(text):
            paths.append((spec["path"], name, value))
    return dud, paths, goals


def write_checksums(out: Path) -> int:
    lines, count = [], 0
    for item in sorted(out.rglob("*")):
        if item.is_file() and item.name not in {"SHA256SUMS", MARKER}:
            digest = hashlib.sha256(item.read_bytes()).hexdigest()
            lines.append(f"{digest}  {item.relative_to(out).as_posix()}")
            count += 1
    (out / "SHA256SUMS").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count


def _oracle_block(spec: dict) -> str:
    """The expected values for one experiment, or an honest note that we have none."""
    oracle = ORACLE.get(spec["path"])
    if not oracle:
        return ("**Expected values:** none recorded. This program is a pass/fail check; "
                "there is no number here to compare.\n")
    tol = oracle["tolerance"]
    how = ("compared **exactly** -- these do not move" if tol == 0
           else f"compared to within **{tol:g}**, except where a row says exact")
    rows = "\n".join(f"| `{name}` | `{value}` | {why} |"
                      for name, value, why in oracle["values"])
    return f"""**Expected values**, {how}.

| goal | our value | |
|---|---|---|
{rows}

*Where these come from:* {oracle['provenance']}

{oracle['note']}
"""


def write_readme(out: Path, paths: list[tuple[str, str, str]],
                 goals: dict[str, int], with_model: bool) -> None:
    lock = out / "implementation/python/requirements.lock"
    n_locked = (len(re.findall(r"^[a-zA-Z].*==", lock.read_text(encoding="utf-8"),
                               re.MULTILINE)) if lock.exists() else 0)
    """Write the reviewer's instructions: one numbered section per experiment.

    Generated rather than kept by hand, so it cannot drift from the manifest:
    the table, the commands and the goal counts all come from PROGRAMS and from
    the copied files themselves.
    """
    def _needs(s):
        if not s["needs_dataset"]:
            return "**none**"
        return "BraTS2020 + GPU" if s.get("needs_gpu") else "BraTS2020"

    index_rows = "\n".join(
        f"| {i} | {s['title']} | {_needs(s)} | {s['minutes']} | {goals[s['path']]} "
        f"| {s['reproducibility']} "
        f"| {'yes, section C' if s['path'] in ORACLE else 'none (pass/fail)'} |"
        for i, s in enumerate(PROGRAMS, 1))

    sections = []
    for i, spec in enumerate(PROGRAMS, 1):
        expect = "\n".join(f"- {e}" for e in spec["expect"])
        data_line = ("This program needs **no data**. If it fails, the problem is the\n"
                     "install, not the dataset.\n"
                     if not spec["needs_dataset"] else
                     "This program needs BraTS 2020. Set its path first -- see section B.\n")
        if spec["reproducibility"].startswith("no"):
            data_line += (
                "\n**Not bit-reproducible, by construction.** It trains a network: GPU\n"
                "kernel non-determinism and the training seed mean your Dice values will\n"
                "differ from ours in the last digits, and from your own second run. What\n"
                "should reproduce is the SHAPE of the result -- the spread of winning\n"
                "thresholds -- not the digits. Every other experiment here is\n"
                "bit-identical; this one is the exception and says so.\n")
        if spec.get("needs_gpu"):
            data_line += ("\nIt also needs `work_root` set to the shipped model directory --\n"
                          "one line, explained in **section F**. Do that before running, or it\n"
                          "trains from scratch for hours.\n")
            data_line += ("\nA CUDA GPU is assumed (`nnunet_device = \"cuda\"` in the\n"
                          "program). Set it to `\"cpu\"` to run without one, and expect it\n"
                          "to take very much longer.\n")
        sections.append(f"""### {i}. {spec['title']}

{spec['note']}

{data_line}
```bash
./voxlogica run {spec['path']}
```

Expected: **exit status 0**, {goals[spec['path']]} named goal{'' if goals[spec['path']] == 1 else 's'} printed as JSON,
and {spec['total_files']} file{'' if spec['total_files'] == 1 else 's'} under
`{spec['outputs']}`. Time: {spec['minutes']}.

What a good run shows:

{expect}

Check the files:

```bash
find {spec['outputs'].split()[0]} -type f | wc -l     # {spec['total_files']}
```

If the count is lower, some writes were never demanded rather than attempted
and failed; see section D.

{_oracle_block(spec)}
""")

    to_edit = "\n".join(f"| `{p}` | `{n}` | `{v}` |" for p, n, v in paths) or \
              "| — | — | none found |"

    model_section = (
        "**The program always calls `nnunet.train`, and that is expected.** `train`\n"
        "skips the training when a trained model is already present in `work_root`.\n"
        "For each fold it looks for\n\n"
        "```\n"
        "<work_root>/nnUNet_results/Dataset900_BraTS2020WholeTumour/nnUNetTrainer__nnUNetPlans__3d_fullres/fold_0/checkpoint_final.pth\n"
        "```\n\n"
        "and if that file exists it logs\n"
        "`Skipping 3d_fullres fold 0 (checkpoint already exists)` and moves on. Check\n"
        "the log for that line: with it, experiment 4 takes about three minutes;\n"
        "without it, the network trains for hours.\n\n"
        "So loading the model means three things:\n\n"
        "1. **`model/` is a populated `work_root`**, rather than a single weights file.\n"
        "   holds the checkpoint at that exact path plus `plans.json`,\n"
        "   `dataset.json`, `dataset_fingerprint.json` and `postprocessing.pkl` --\n"
        "   what `train` needs to find everything in place. You set one line in\n"
        "   the program, as section B says: `work_root = \"<this directory>/model\"`.\n"
        "2. **The names must match.** The path is built from the program's\n"
        "   `dataset_name`, `nnunet_trainer` and `nnunet_config`. If any of them is\n"
        "   changed, `train` finds no checkpoint and retrains from scratch, without\n"
        "   warning and for hours. Leave them as shipped.\n"
        "3. **It saves the training, not the dataset.** Preprocessing runs before\n"
        "   the checkpoint check, so the 50 training cases are still read and\n"
        "   preprocessed under `model/`. Without BraTS the program cannot run at\n"
        "   all, weights or no weights.\n\n"
        "`postprocessing.pkl` is 260 bytes and easy to overlook. It records the\n"
        "decision nnU-Net took on its validation set: keep only the largest\n"
        "connected component. Without it the run still succeeds, but predictions\n"
        "come out raw and every number is off by about 1e-2 against the expected\n"
        "values. Do not delete it.\n\n"
        "`model/voxlogica_manifest.json` records what these weights are -- dataset,\n"
        "trainer, configuration, folds, postprocessing -- and is rewritten by each\n"
        "run. The training DATA is not here and cannot be: it is BraTS, rewritten.\n"
        "(`nnunet.train` also accepts a `pretrained` argument. That serves a different\n"
        "purpose -- weights to initialise a new training from -- and is not needed here.)\n"
        if with_model else
        "Not included in this build. Rebuild with `--with-model` to add it.\n")

    (out / "README.md").write_text(f"""# VoxLogicA-2 — TACAS artifact

Built from the repository by `tools/make_artifact.py`; `PROVENANCE.json` records
the exact commit.

| # | experiment | needs | time | goals | reproducible | expected values |
|---|---|---|---|---|---|---|
{index_rows}

Read sections 0, A and B once, then run the experiments in order.
**Experiment 1 needs nothing but this directory** -- start there.

License: GPL-3.0, see `LICENSE`. Source: https://github.com/VoxLogicA-Project/VoxLogicA-2
(the commit is in `PROVENANCE.json`).

## Early light review (kick-the-tires) -- about 5 minutes, no dataset

**This section is the whole kick-the-tires phase.** It needs no BraTS, no GPU
and no large machine, and it is enough to tell whether the artifact is sound.
None of the four experiments has to run to pass it; they belong to the full
evaluation, and the shortest of them still takes about an hour.

```bash
# 1. the shipped files are intact
sha256sum -c SHA256SUMS | grep -vc ': OK$'                 # 0

# 2. the tool builds itself (downloads ~3 GB once; network needed here)
./voxlogica --help                                         # a usage message

# 3. every shipped program is well-formed against the engine that ships with it
for p in doc/gallery/programs/*/*.imgql; do
  ./voxlogica run --no-serve --no-execute "$p" && echo "ok $p"
done                                                       # ok, five times

# 4. the engine actually computes -- one second, no data
./voxlogica run --no-serve doc/gallery/programs/default/default-range-map.imgql
```

The last command must print exactly:

```
squares=[0.0, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0, 121.0, 144.0, 169.0, 196.0, 225.0, 256.0, 289.0, 324.0, 361.0]
```

Step 3 parses, reduces and type-checks each program without computing anything;
step 4 computes. Together they show that the environment is complete and the
engine works end to end.

If all four steps pass, the artifact is ready for the full evaluation. A good
next move is to start experiment 1 in the background -- it needs no dataset
either, but takes 51 minutes on 24 cores and 77 on 4, at 1.2 GB of memory --
and meanwhile obtain BraTS as section B describes.

## Resources

| | |
|---|---|
| Disk | 25 GB free, dataset excluded (venv 8 GB, ~5 GB of results store per sweep) |
| RAM, measured peak | depends on parallelism. At 24 threads: experiment 2: 8.8 GB; 3: 4.5 GB; **4: 20 GB**. At 4 threads (`--threads 4`): experiment 1: 1.2 GB; 2: 1.9 GB; 3: 2.4 GB. A VM with 8 GB runs experiments 1, 2 and 3; experiment 4 does not start in 8 GB -- see below |
| CPU | any; the engine uses every core it finds. Times in this README are from a 24-core machine |
| GPU | **experiment 4 only** (`nnunet_device = "cuda"`). Without one it can run on CPU -- set the device to `"cpu"` -- but we have not timed that |
| Network | once, during bootstrap; every download is version-pinned and hash-checked |
| OS | Linux x86-64 is what we measured on. `bootstrap.py` fetches its own interpreter, so the host Python does not matter |

In a virtual machine: experiments 1, 2 and 3 fit, measured in an Ubuntu 22.04
container with 4 cores, 8 GB and no GPU -- experiment 1 in 77 min, 2 in 31 s,
3 in 3 min.

Experiment 4 does not. With 8 GB it is killed by the out-of-memory killer after
24 seconds, inside `nnUNetv2_plan_and_preprocess` -- before any prediction and
before the GPU would matter at all. Preprocessing 50 BraTS cases at
`3d_fullres` is what does not fit. So the obstacle is memory first and the GPU
second, and we have asked the chairs for the hardware exemption the call
provides.

---

## 0. Check the shipped files -- before you touch anything

```bash
sha256sum -c SHA256SUMS
```

Every line must end in `OK`. Do this FIRST: section B has you edit two
program files, and running experiment 4 rewrites `model/voxlogica_manifest.json`,
so a check made afterwards reports exactly those files as changed. Running it
now, before any edit, is the only time the result is informative.

## A. Build the tool

```bash
./voxlogica --help
```

The first call runs `bootstrap.py`, which downloads a pinned `uv`, reads
`.python-version` and creates `.venv` here. Measured: 137 packages in 44 s on
a fast connection. It is idempotent: re-run it freely.

**Disk: have 25 GB free before you start**, dataset excluded. The venv is
8 GB (torch and its CUDA libraries are most of it), each of the two sweeps
writes a ~5 GB results store, and the nnU-Net experiment preprocesses ~2 GB
under `model/`. We filled a disk twice running this. The symptoms are indirect: the engine
warns once with `cache budget cut from ... by free space`, and the run later
fails with `image must be a SimpleITK Image, got NoneType`. If you see either
message, check free space and rerun.

Every version is pinned. `implementation/python/requirements.lock` resolves the
whole transitive graph -- {n_locked} packages, each with its sha256 -- and that
is what gets installed. A package re-uploaded under the same version fails the
install rather than substituting itself. The last line of the bootstrap output
says which path was taken; it must read

```
Environment synchronized with the hashed lock files.
```

If it instead mentions `requirements.txt (NO LOCK FILE ...)`, the lock did not
travel with this artifact and versions can drift. Say so in your review.

Two requirements:

1. **Free-threaded CPython.** `.python-version` asks for `3.14t`. The engine
   refuses a stock build rather than running serialized, and says so.
2. **Always launch through `./voxlogica`.** It exports `PYTHON_GIL=0` before
   the interpreter starts (too late to set from Python) and puts `.venv/bin` on
   `PATH`, which is where nnU-Net's own executables live. Calling
   `python -m voxlogica.main` directly appears to work and then fails inside
   nnU-Net with `No such file or directory: nnUNetv2_plan_and_preprocess`.

## B. Point the programs at your copy of BraTS

The datasets are not here: the BraTS data-use agreement does not let us
redistribute them, so you have to obtain them yourself. Experiment 1 needs
none of this.

**Where to get BraTS 2020.** The training data is mirrored on Kaggle:

    https://www.kaggle.com/datasets/awsaf49/brats2020-training-data

You need a Kaggle account. The official source is the challenge organisers
(CBICA, University of Pennsylvania), who require a registration; the Kaggle
mirror is the same 369 cases and is what most people use.

**Two things to check about the copy you download**, because we built our
manifest on the official release and have not verified the Kaggle mirror's
layout ourselves:

1. **Compression.** The programs look for `*_flair.nii.gz` etc. Public
   notebooks on the Kaggle mirror refer to uncompressed `.nii` files; if that
   is what you have, gzip them in place first:
   `find <root> -name '*.nii' -exec gzip {{}} +`. With the wrong suffix `dir`
   finds nothing at all, and the manifest check below reports 0 files against
   369.
2. **One misnamed file.** The same notebooks mention that case
   `BraTS20_Training_355` ships its segmentation under a different name
   (`W39_1998.09.19_Segm.nii`). If so, rename it to
   `BraTS20_Training_355_seg.nii.gz` after gzipping, or that case is silently
   missing from `*_seg.nii.gz` and every position after 354 shifts.

Either way, run the manifest check below before anything else: it compares the
ordered listing and the hashes, and will name exactly what differs.

Each program names its dataset root as a literal near the top. These are the
lines to edit:

| program | variable | value as shipped |
|---|---|---|
{to_edit}

The five-case sampler additionally wants five specific cases in
`doc/gallery/programs/brats2020/data/`, one directory each, exactly as BraTS
ships them; `doc/gallery/programs/brats2020/data/README.md` names the five.

**A wrong path does not pass silently.** `dir` fails when its root does not
exist, and the engine refuses a program whose goals would compute nothing.

### Check that your BraTS is the same BraTS

```bash
python3 tools/dataset_manifest.py /path/to/MICCAI_BraTS2020_TrainingData
```

Expected: `OK: this dataset matches the one the expected values were measured
on.` and exit status 0. It takes a few seconds; `--quick` skips the hashing and
compares sizes only.

**What this protects against.** The experiments select cases by POSITION --
`subsequence(dir(...), 0, case_count)` in the AIIM sweep, `train_start` and
`eval_start` in the nnU-Net one. One case missing, one extra, or a stray file
matching the glob shifts every position after it onto a different case. The run
still succeeds and the Dice values still look reasonable, but they describe a
different set of patients, and nothing in the output indicates this.

The check therefore compares the ORDERED listing rather than counting files,
and on a mismatch it reports the index where the two diverge. Everything from
that index onwards is reading data we did not measure.

It also checks `name_mapping.csv`, the metadata file BraTS ships beside the
cases. The nnU-Net experiment selects its population from it -- the 293 cases
whose first field says `HGG` -- so a copy of BraTS without that file cannot run
experiment 4 at all, and a copy with a DIFFERENT one runs it on a different
population. The check reproduces the selection and names the first case it
would pick differently.

Symlinks are fine -- to the whole dataset, to case directories, or to files;
`dir` follows them. One thing to know: with `full_paths` the programs sort by
the path each link RESOLVES TO, so links that point to scattered places can
come out in an order your directory listing does not show. Linking from one
place keeps the two orders the same, and the check above will say if they are
not.

## C. Run the experiments

{"".join(sections)}
---

## D. Two behaviours worth knowing about

**A second run finishes instantly and writes no files.** Results are cached in
`~/.voxlogica`, keyed by content, so re-running an unchanged program returns the
stored values without recomputing -- and therefore without re-writing the
images. This is the intended behaviour. To force real computation:

```bash
./voxlogica run --no-cache <program>       # no disk tier at all
```

**Do not run the same experiment twice at the same time.** The smoke test puts
its training tree in a fixed directory under `/tmp`, and experiment 4 puts its
preprocessing under `model/`; two concurrent runs of the same program share that
directory and corrupt each other's preprocessing. Run them one after another.

## E. Reproducibility

`--threads N` fixes the degree of parallelism. Results are **bit-identical**
across thread counts -- verified at 1, 4 and 16 threads on experiment 3, and
identical again to a warm-cache run. Only the wall time changes. So a number
that differs on your machine is not the scheduler.

The nnU-Net programs are the exception: GPU non-determinism and training seeds
mean their predictions are not reproducible bit-for-bit unless you use the
shipped weights rather than retraining.

## F. The trained model

{model_section}
""", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the TACAS artifact directory.")
    ap.add_argument("--out", default=str(REPO.parent / "voxlogica-tacas-artifact"),
                    help="output directory (default: beside the repository)")
    ap.add_argument("--with-model", action="store_true",
                    help="include the trained nnU-Net weights (~240 MB)")
    ap.add_argument("--tar", action="store_true", help="also write a .tar.gz beside it")
    ap.add_argument("--zip", action="store_true",
                    help="also write a .zip beside it (EasyChair wants a ZIP)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite --out even if this script did not build it")
    args = ap.parse_args()

    out = Path(args.out).expanduser().resolve()
    started = time.time()
    print(f"repository : {REPO}\nartifact   : {out}")

    step(1, f"Preparing {out}")
    prepare_out(out, args.force)

    step(2, f"Copying the engine ({len(ENGINE)} entries)")
    files = size = 0
    for rel in ENGINE:
        src = REPO / rel
        if not src.exists():
            sys.exit(f"missing from the checkout: {rel}")
        f, s = copy_tree(src, out / rel)
        files += f
        size += s
        print(f"    {rel}  ({f} files, {human(s)})")

    step(3, f"Copying {len(PROGRAMS)} programs")
    for spec in PROGRAMS:
        src = REPO / spec["path"]
        if not src.exists():
            sys.exit(f"missing from the checkout: {spec['path']}")
        f, s = copy_tree(src, out / spec["path"])
        files += f
        size += s
        print(f"    {spec['title']}: {spec['path']}")

    step(4, "Placeholder for the five-case sample (no image data is copied)")
    data_dir = out / "doc/gallery/programs/brats2020/data"
    data_dir.mkdir(parents=True, exist_ok=True)
    cases = sorted(p.name for p in (REPO / "doc/gallery/programs/brats2020/data").iterdir()
                   if p.is_dir()) if (REPO / "doc/gallery/programs/brats2020/data").exists() else []
    (data_dir / "README.md").write_text(
        "# The five-case sample\n\n"
        "Empty on purpose. BraTS may not be redistributed, so these five cases have\n"
        "to come from your own copy of MICCAI_BraTS2020_TrainingData. Copy or symlink\n"
        "one directory per case, exactly as BraTS ships them (five files inside:\n"
        "`_flair`, `_t1`, `_t1ce`, `_t2`, `_seg`):\n\n"
        + "".join(f"- `{c}`\n" for c in cases)
        + "\nThe program reads them with `dir(..., recursive)`, so the directory names\n"
          "matter only for your own bookkeeping; the file suffixes matter.\n",
        encoding="utf-8")
    print(f"    named {len(cases)} cases, copied 0 images (BraTS policy)")

    step(5, "Trained model")
    if args.with_model:
        src = MODEL["source"]
        if not src.exists():
            sys.exit(f"--with-model asked for, but {src} does not exist")

        # WHAT THE WEIGHTS SAY THEY ARE, from the run that produced them.
        shipped = {}
        manifest = MODEL["manifest"]
        if manifest.exists():
            m = json.loads(manifest.read_text(encoding="utf-8"))
            shipped = {"dataset_name": m.get("dataset_name", ""),
                       "trainer": m.get("trainer", ""),
                       "configuration": m.get("configuration", "")}
            sel = (m.get("selection") or [{}])[0]
            shipped["trainer"] = shipped["trainer"] or sel.get("trainer", "")

        # WHAT THE SHIPPED PROGRAMS ASK FOR.
        wanted, consumers = {}, []
        for spec in PROGRAMS:
            text = (out / spec["path"]).read_text(encoding="utf-8")
            found = {k: (r.search(text).group(1) if r.search(text) else "")
                     for k, r in MODEL_SETTINGS_RE.items()}
            if any(found.values()):
                consumers.append((spec["path"], found))
                wanted = found

        if not consumers:
            sys.exit("--with-model asked for, but no shipped program names an "
                     "nnU-Net model. The weights would be 236 MB nothing can use.")

        mismatch = {k: (wanted[k], shipped.get(k, "")) for k in MODEL_SETTINGS_RE
                    if shipped and wanted[k] != shipped.get(k, "")}
        for path, found in consumers:
            print(f"    consumer: {Path(path).name}")
        if shipped:
            print(f"    shipped weights: {shipped['dataset_name']} / "
                  f"{shipped['trainer']} / {shipped['configuration']}")
        if mismatch:
            detail = "; ".join(f"{k}: program wants {w!r}, weights are {g!r}"
                               for k, (w, g) in mismatch.items())
            sys.exit("the weights do not match what the shipped program asks for, "
                     "so nnU-Net would ignore them and retrain:\n  " + detail +
                     "\nAlign the program's constants with the weights (or "
                     "retrain), then rebuild.")

        kept = 0
        for item in sorted(src.rglob("*")):
            if item.is_file() and item.name in MODEL["keep"]:
                target = out / MODEL["dest"] / item.relative_to(src)
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, target)
                kept += 1
                files += 1
                size += target.stat().st_size
                print(f"    {item.relative_to(src)}  ({human(target.stat().st_size)})")
        if manifest.exists():
            shutil.copy2(manifest, out / "model" / manifest.name)
            kept += 1
        print(f"    kept {kept} files; refused {', '.join(MODEL['refused'])} "
              f"(BraTS-derived volumes)")
    else:
        print("    skipped (pass --with-model to include ~240 MB of weights)")

    step(6, "Checking the programs")
    shipped = {spec["path"] for spec in PROGRAMS}
    orphaned = sorted(set(ORACLE) - shipped)
    if orphaned:
        sys.exit("ORACLE has expected values for programs this artifact does not "
                 "ship:\n  " + "\n  ".join(orphaned))
    dud, paths, goals = check_programs(out)
    for program, name, value in paths:
        print(f"    {Path(program).name}: {name} = {value}")
    if dud:
        sys.exit("these programs have no print/save goal and would compute "
                 "nothing:\n  " + "\n  ".join(dud))
    print("    " + ", ".join(f"{Path(s['path']).name}: {goals[s['path']]} goals"
                             for s in PROGRAMS))
    print(f"    {len(paths)} paths for the reviewer to set")

    step(7, "Writing README.md and PROVENANCE.json")
    write_readme(out, paths, goals, args.with_model)
    dirty = bool(git("status", "--porcelain", "--untracked-files=no"))
    (out / "PROVENANCE.json").write_text(json.dumps({
        "built_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "built_by": "tools/make_artifact.py",
        "git_commit": git("rev-parse", "HEAD"),
        "git_branch": git("rev-parse", "--abbrev-ref", "HEAD"),
        "git_describe": git("describe", "--always", "--dirty"),
        "working_tree_dirty": dirty,
        "python_version_file": (REPO / ".python-version").read_text(encoding="utf-8").strip(),
        "builder_python": sys.version.split()[0],
        "programs": [s["path"] for s in PROGRAMS],
        "includes_model": args.with_model,
        "includes_dataset": False,
    }, indent=2) + "\n", encoding="utf-8")
    if dirty:
        print("    WARNING: working tree has uncommitted tracked changes; "
              "the commit in PROVENANCE.json does not describe what was copied")

    step(8, "Writing SHA256SUMS")
    print(f"    {write_checksums(out)} files hashed")

    tarball = None
    if args.tar:
        step(9, "Writing the tarball")
        tarball = out.with_suffix(".tar.gz")
        with tarfile.open(tarball, "w:gz") as tf:
            tf.add(out, arcname=out.name)
        print(f"    {tarball}  ({human(tarball.stat().st_size)})")

    zipball = None
    if args.zip:
        step(10 if args.tar else 9, "Writing the zip")
        import zipfile
        zipball = out.with_suffix(".zip")
        with zipfile.ZipFile(zipball, "w", zipfile.ZIP_DEFLATED) as zf:
            for item in sorted(out.rglob("*")):
                if item.is_file():
                    zf.write(item, (out.name / item.relative_to(out)).as_posix())
        print(f"    {zipball}  ({human(zipball.stat().st_size)})")

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    count = sum(1 for f in out.rglob("*") if f.is_file())
    print(f"\n{'=' * 62}\n"
          f"  artifact   {out}\n"
          f"  files      {count}\n"
          f"  size       {human(total)}\n"
          f"  model      {'included' if args.with_model else 'not included'}\n"
          f"  dataset    never included (BraTS policy)\n"
          + (f"  tarball    {tarball}\n" if tarball else "")
          + (f"  zip        {zipball}\n" if zipball else "")
          + f"  built in   {time.time() - started:.1f} s\n"
          f"{'=' * 62}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
